---

- hosts: all
  gather_facts: no
  become: yes
  become_method: su
  
  tasks:
    - name: Applying NTP firewall configuration
      shell: firewall-cmd --add-service=ntp --permanent

    - name: Applying HTTP firewall configuration
      shell: firewall-cmd --add-service=http --permanent

    - name: Applying HTTPS firewall configuration
      shell: firewall-cmd --add-service=https --permanent

    - name: Applying SSH firewall configuration
      shell: firewall-cmd --add-service=ssh --permanent

    - name: Reload firewall configuration
      shell: firewall-cmd --reload
  
    - name: Enabling HTTPS proxy configuration
      shell: export https_proxy=172.16.3.80:8282

    - name: Enabling HTTP proxy configuration
      shell: export http_proxy=172.16.3.80:8282
 
    - name: Installing EPEL repositories
      yum: name=epel-release state=installed
  
    - name: Updating repositories
      yum: update_only=yes
      
    - name: Installing Chrony
      yum: name=chrony state=latest
