---
- hosts: dbservers
  become: yes
  become_method: su

  tasks:
  - name: Check if a certificate is currently still valid, ignoring failures
    openssl_certificate:
      path: /etc/httpd/conf/ssl.crt/server.crt
      provider: assertonly
      has_expired: no
    ignore_errors: yes
    register: cert


  - name: Show certificate information
    debug:
      var: cert

#  - name: Get a cert from an https port
#    get_certificate:
#      host: "ceetelco.sharepoint.com"
#      host: "172.16.103.22"
#        - "ceetelco.sharepoint.com"
#      port: 443
#    delegate_to: localhost
#    run_once: true
#    register: cert

#  - name: How many days until cert expires
#    debug:
#      msg: "cert expires in: {{ expire_days }} days."
#    vars:
#      expire_days: "{{ (( cert.not_after | to_datetime('%Y%m%d%H%M%SZ')) - (ansible_date_time.iso8601 | to_datetime('%Y-%m-%dT%H:%M:%SZ')) ).days }}"


#  name: Ensure that a certificate uses a modern signature algorithm (no SHA1, MD5 or DSA)
#  openssl_certificate:
#    path: /etc/ssl/crt/example.com.crt
#    provider: assertonly
#    signature_algorithms:
#      - sha224WithRSAEncryption
#      - sha256WithRSAEncryption
#      - sha384WithRSAEncryption
#      - sha512WithRSAEncryption
#      - sha224WithECDSAEncryption
#      - sha256WithECDSAEncryption
#      - sha384WithECDSAEncryption
#      - sha512WithECDSAEncryption

