---
- hosts: dbservers
  tasks:
    - name: Get information on generated certificate
      openssl_certificate_info:
        path: /etc/httpd/conf/ssl.crt/server.crt
      register: result

    - name: Dump information
      debug:
        var: result.not_after
