---
- hosts: all
  become: yes
  become_method: su
 # gather_facts: false

  tasks:
    - name: Distribution
      debug:
        msg: "{{ ansible_facts.distribution }} {{ ansible_facts.distribution_version }}"

