---
- hosts: webservers
  become: yes
  become_method: su
  tasks:
    - name: Create Groups
      group:
        name: "{{ item }}"
      loop:
        - john
        - doe

    - name: Create User
      user:
        name: "{{ item.name }}"
        group: "{{ item.group }}"
        groups: "{{ item.groups }}"
        password: "{{ item.password }}"
#        password: "{{ item.password  | password_hash('sha512') }}"
        state: "{{ item.state }}"
      loop:
        - { name: 'john', group: 'john', groups: 'wheel', password: '', state: 'present' }
        - { name: 'doe', group: 'doe', groups: 'wheel', password: '', state: 'present' }

    - name: Force user password change
      command: chage -d 0 "{{ item }}"
      loop:
        - john
        - doe

    - name: Install SSH key
      authorized_key:
        user: "{{ item.user }}"
        key: "{{ item.key }}"
        state: "{{ item.state }}"
        comment: "{{ item.comment }}"
      loop:
        - { user: 'john', key: "{{ lookup('file', '/home/john/.ssh/id_dsa.pub') }}, state: 'present', comment: 'john key' }
        - { user: 'doe', key: "{{ lookup('file', '/home/doe/.ssh/id_dsa.pub') }}, state: 'present', comment: 'doe key' }
