---
- name: Remove Azure instance
  hosts: localhost
  connection: local
  gather_facts: no
  
  tasks:
#  - name: Get VM List
#    azure_rm_virtualmachine_facts:
#      resource_group: jacek-demo
#      
#  - name: Show Vms List
#    debug:
#      var: vms
  
  - name: Remove a VM and all resources that were autocreated
    azure_rm_virtualmachine:
      resource_group: jacek-demo
      name: "{{ azure_vm_name }}"
      remove_on_absent: all
      state: absent