---
- name: Create VM on VMware
  hosts: localhost
  connection: local
  
  vars:
    vmware_vm_name: vmwaredemovm001
    vmware_template_name: rhel7-vmware-template
    vm_memory: 1024
    vcpu_cpunt: 2
  
  tasks:
  - name: Create a virtual machine from a template
    vmware_guest:
#      hostname: "{{ vcenter_hostname }}"
#      username: "{{ vcenter_username }}"
#      password: "{{ vcenter_password }}"
#      validate_certs: no
      name: "{{vmware_vm_name}}"
      state: poweredon
      datacenter: Datacenter
      template: "{{ vmware_template_name }}"
      folder: /Datacenter/vm
      hardware:
        memory_mb: "{{ vm_memory }}"
        num_cpus: "{{ vcpu_count }}"
      networks:
      - name: VM Network
      wait_for_ip_address: yes
    register: deploy